apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-img-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-web-img
  template:
    metadata:
      labels:
        app.kubernetes.io/name: argocd-web-img
    spec:
      containers:
      - name: argocd-img
        image: gjwnsgud4016/app-with-argocd-img:f77886b8142cf826ecdfed2fbd88154b4279ddcf9690fb7e015e23dc1906b2679006248999f32d7
