name: App With Github Actions with ArgoCD

on:
  workflow_dispatch
  # push

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Make application.properties
      run: |
        mkdir -p ./src/main/resources
        cd ./src/main/resources
        touch ./application.properties
        echo "${{ secrets.PROPERTIES }}" > ./application.properties
      shell: bash

    - name: Build with Maven
      run: mvn -B -DskipTests package --file pom.xml
      
    - name: Naming jar file
      run: mv ./target/*.jar ./target/app.jar

    - name: Check jar file
      run: ls ./target

    - uses: actions/upload-artifact@v4
      with:
        name: app
        path: ./target/*.jar

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPOSITORY }}:${{ github.sha }}

  cd:
    runs-on: ubuntu-latest
    needs: ci
      
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}  # 현재 브랜치 사용
        token: ${{ secrets.GH_TOKEN }}
        fetch-depth: 0  # 전체 히스토리 가져오기
  
    - name: Debug directory structure
      run: |
        echo "Current directory: $(pwd)"
        ls -R
        echo "Manifest file content:"
        cat ./manifest/argocd-img-deployment.yaml || echo "File not found"
  
    - name: Update image tag
      run: |
        echo "Updating image to: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPOSITORY }}:${{ github.sha }}"
        sed -i "s|image: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPOSITORY }}:latest|image: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPOSITORY }}:${{ github.sha }}|" ./manifest/argocd-img-deployment.yaml
        echo "Updated file content:"
        cat ./manifest/argocd-img-deployment.yaml
        git diff  # 변경사항 확인
  
    - name: Commit and push changes
      run: |
        git config --local user.email "gjwnsgud4016@gmail.com"
        git config --local user.name "HeoJunHyoung"
        git add .
        if ! git diff --cached --quiet; then
          git commit -m "Update image to ${{ github.sha }}"
          git push
        else
          echo "No changes to commit"
          exit 1
        fi
